site_name: ECE 5760 Final Project
site_description: Static project website for the ECE 5760 Bayesian-network FPGA project.
site_url: https://iwgithub2.github.io/ece5760-final-project-mkdocs/
repo_url: https://github.com/iwgithub2/ece5760-final-project-mkdocs
repo_name: iwgithub2/ece5760-final-project-mkdocs

docs_dir: docs
site_dir: site
use_directory_urls: true

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Home: index.md
  - Research Notes: research.md
  - Implementation: implementation.md
  - Updating the Site: updating.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - fenced_code
  - tables
  - toc:
      permalink: true
